jupyter_book_task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  auto_cancellation: true
  env:
    NPROC: 2
    GH_TOKEN: ENCRYPTED[!1695a1dc15db89867633ee9a039d510ba95371283caa77b353163ccfb463ccd6c51a9a1d4130906fd4f2abb6333d8a56!]
    GKSwstype: 100
    JULIA_PROJECT: $CIRRUS_WORKING_DIR
    JULIA_DEPOT_PATH: /tmp/juliapkg/
    JULIA_NUM_PRECOMPILE_TASKS: 4
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  julia_cache:
    folder: $JULIA_DEPOT_PATH
    fingerprint_script:
      - echo $CIRRUS_OS
      - julia --version
      - cat Manifest.toml
  julia_dep_script: julia --color=yes -e 'import Pkg; Pkg.instantiate(); Pkg.resolve();
  upload_notebook_script: |
    if [[ $CIRRUS_BRANCH == 'main' ]]; then
      echo "Uploading notebooks"
      mkdir -p out
      cp *.toml *.txt *.md out/
      cp -R docs out/
      cp -R src out/
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -nofp -b out out/
      rm -rf out/
    fi
  literate_script: julia --color=yes -p $NPROC literate.jl
  jbook_script: jupyter-book build docs/ --keep-going
  ## Requires a repo scope access GitHub PAT encrypted to `GH_TOKEN` to push to its GitHub repo
  pages_script: |
    if [[ $CIRRUS_BRANCH == 'main' ]]; then
      echo "Deploying to GitHub pages..."
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -nofp docs/_build/html
    fi
