jupyter_book_task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  auto_cancellation: true
  env:
    NPROC: 2
    GKSwstype: 100
    JULIA_PROJECT: $CIRRUS_WORKING_DIR
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  literate_script: julia -p ${NPROC} literate.jl
  notebooks_artifacts:
    path: "docs/**"
