jupyter_book_task:
  env:
    NPROC: 1
    GH_TOKEN: ENCRYPTED[!1695a1dc15db89867633ee9a039d510ba95371283caa77b353163ccfb463ccd6c51a9a1d4130906fd4f2abb6333d8a56!]
    GKSwstype: 100
    JULIA_PROJECT: $CIRRUS_WORKING_DIR
  auto_cancellation: true
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  literate_script: julia --color=yes -p $NPROC literate.jl
  upload_notebook_script: |
    if [[ $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ]]; then
      echo "Uploading notebooks"
      echo ".cirrus.yml" >> .gitignore
      echo ".github/" >> .gitignore
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -nofpb out $CIRRUS_WORKING_DIR
    fi
  jbook_script: jupyter-book build docs/ --keep-going
  ## Requires a repo scope access GitHub PAT encrypted to `GH_TOKEN` to push to its GitHub repo
  pages_script: |
    if [[ $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ]]; then
      echo "Deploying to GitHub pages"
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -nofp docs/_build/html
    fi
