ci_task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_BASE_BRANCH == 'main' || $CIRRUS_TAG != ''
  auto_cancellation: true
  env:
    NPROC: '2'
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  literate_script: |
    JULIA_PROJECT=@. julia --color=yes --heap-size-hint=3500m -p ${NPROC} literate.jl
  notebooks_artifacts:
    path: "docs/**"
