name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-manifest.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write
    uses: sosiristseng/juliabook/.github/workflows/update-manifest.yml@main
    with:
      julia-version: '1'
    secrets:
      APP_ID: ${{ secrets.APP_ID }} # https://github.com/apps/wen-wei-s-pr-bot
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
